### PR TITLE
Replace k8s.gcr.io references with registry.k8s.io

### PR DESCRIPTION
**Pull request by asa3311**
Replace k8s.gcr.io references with registry.k8s.io

### CODE REVIEW

**Comment by kvaps** [comment]
Hi @asa3311 please bump the patch version of helm chart

https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/0fa28a3bf422471851704e6192c0ea7e97489a19/charts/nfs-server-provisioner/Chart.yaml#L5

**Comment by asa3311** [comment]
> Hi @asa3311 please bump the patch version of helm chart
> 
> https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/0fa28a3bf422471851704e6192c0ea7e97489a19/charts/nfs-server-provisioner/Chart.yaml#L5

done

**Comment by asa3311** [comment]
> Hi @asa3311 please bump the patch version of helm chart
> 
> https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/0fa28a3bf422471851704e6192c0ea7e97489a19/charts/nfs-server-provisioner/Chart.yaml#L5

done

**Comment by asa3311** [comment]
done

**Review by kvaps — APPROVED** [review]
/lgtm

**Pull request merged**
