### PR TITLE
helm: template refactoring

### LINKED ISSUE #19: Update Helm chart with current best practices - PRs wanted?
As Helm has developed over time, various best practices has been updated. I'd be happy to contribute PRs that would make this Helm chart up to date with such practices. But, I'd like some input with regards to if that would be wanted, and if it could be okay to make some breaking changes at this time.

I figure since this Helm chart isn't being published right now, it would be suitable to do breaking changes now before it becomes published again, for example at https://artifacthub.io/ which is the new Helm Hub location.

## Breaking changes examplified
- _Use modern labels, so instead of `app` it would be `app.kubernetes.io/name`  (like discussed for this Helm chart: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1867)._
  This is tricky to update with `helm3 upgrade` even though it was quite easy with `helm2 upgrade --force`, so if it is ever to be done, it's good to do sooner rather than later in my mind.
- _Apply 
- _Update Chart.yaml to `apiVersion: 2`._
  A change that will make Helm 2 no longer be supported, but Helm 2 reach end of life November 13.

## Non breaking changes examplified
- Apply systematic whitespace chomping practices (always chomp left, almost never chomp right).
- Use `{{- with ... }}` instead of `{{- if }}` when it makes sense
- Use `include` instead of `template`.
- Use `nindent` with whitespace chomping left instead of `indent` when using `toYaml`
- Follow indentation practices for readability

## Feedback wanted
Would you be open to such breaking changes and/or such non breaking changes to the Helm chart?

## About me
I'm maintaining the [JupyterHub Helm chart](https://github.com/jupyterhub/zero-to-jupyterhub-k8s) and have spent a lot of time working with k8s and Helm chart the last ~3 years. I'm motivated to contribute to this project as I think it serves a very important piece in the infrastructure I want to help many others make use of, for example universities that want to provide a compute platform for their researchers and students with personal home directories.

### PR DESCRIPTION
**Pull request by consideRatio**
This is not an important PR, it just makes some template practices a bit more consistently used.

Closes #19.

### CODE REVIEW

**Comment by kvaps** [comment]
@consideRatio thanks for PR, changes are ok, could you also bump the chart version please?

/approve

**Comment by consideRatio** [comment]
@kvaps sorry for the slow turnaround, I rebased and bumped the patch version as this was only helm template refactoring without any actual change to functionality etc.

**Comment by kvaps** [comment]
@consideRatio, thank you for your contribution!
/approove
/lgtm

**Pull request merged**
