### PR TITLE
Update release tools to 5489de6

### PR DESCRIPTION
**Pull request by wongma7**
ran
`git subtree pull --squash --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master`

The latest 5489de6 does not include a .travis.yml: https://github.com/kubernetes-csi/csi-release-tools/pull/136 . From what I can tell this repo does not rely on .travis.yml anymore anyway and have switched to prow GCR builds, and the switch away from .travis.yml already occurred before sept 3 so creds were not leaked. 
https://twitter.com/peter_szilagyi/status/1437646118700175360 . I didn't maintain the travis build or its associated creds since the external-storage repo migration so I'm not sure to what container registry those creds pointed, they need to be rotated/deleted.

/cc @kmova

### CODE REVIEW

**Review by kvaps — APPROVED** [review]

**Comment by wongma7** [comment]
@kvaps I'm not in kubernetes-csi , only in kubernetes-sigs :joy:. I'll try to get myself added but you are free to pick up this PR  in meantime : (

**Comment by wongma7** [comment]
oh I misunderstood what the bot is saying, for some reason it's parsing the release-tools OWNERS?

**Comment by kvaps** [comment]
Yup 🙂

**Comment by wongma7** [comment]
@kvaps I submitted https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/71 to just remove the .travis.yml.

@pohly do you know how we can tell the bot not to parse the release-tools/OWNERS... since we are subtreeing release-tools, the bot is treating the OWNERS file as part of our repo, but our repo is kubernetes-sigs, not kubernetes-csi, so it thinks we dont' have permission to touch release-tools/

**Comment by kvaps** [comment]
@wongma7 could you try to not using `--squash` while pulling changes for the subtree?
I think it might work

**Comment by pohly** [comment]
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons.

This can be fixed by making `OWNERS_ALIASES` at the root a symlink to `release-tools/KUBERNETES_CSI_OWNERS_ALIASES`.

**Comment by pohly** [comment]
Also, please use squashing.

**Review by kvaps — APPROVED** [review]
/lgtm

**Pull request merged**
