### PR TITLE
Enable ppc64le and s390x

### PR DESCRIPTION
**Pull request by yselkowitz**
This is a follow-up to #62

/cc @mkumatag﻿

### CODE REVIEW

**Review by kvaps — APPROVED** [review]

**Comment by consideRatio** [comment]
I have not seen this PR properly tested yet.

Why isn't the GitHub workflows run for this PR? This PR changed a github workflow file, which is declared to make the docker build happen if changed.

**Comment by consideRatio** [comment]
It is tested practically here now at least: https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/runs/4204110789?check_suite_focus=true

**Comment by yselkowitz** [comment]
What is needed to get a new multi-arch release pushed to https://console.cloud.google.com/gcr/images/k8s-staging-sig-storage/global/nfs-provisioner?

**Comment by mkumatag** [comment]
prow job timed out, seems like the default timeout for the prow job is 2hrs which needs to be increased.

prow job location - https://github.com/kubernetes/test-infra/blob/5ff3828d6e726f9c3d6ef6af9a27b8d77617be4c/config/jobs/image-pushing/k8s-staging-sig-storage.yaml#L485:L521

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish ^^

**Comment by mkumatag** [comment]
btw: here is the failed job: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-nfs-ganesha-server-and-external-provisioner-push-images/1459900631392194560

**Comment by mkumatag** [comment]
Created https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/issues/78 to fix the above failure.

**Pull request merged**
