### PR TITLE
Make arm Dockerfile to be a symlink to the x86_64 Dockerfile

### LINKED ISSUE #57: Three Dockerfiles in repo could be a single
In #56 @kvaps suggests to let two dockerfiles be the same Dockerfile. Excellent!

I'm not sure about the status of the arm Dockerfile, but trialing to build the x86_64 arm dockerfile on my arm64 based Raspberry PI 4, it seem to work fine as well.

Perhaps there should simply be one single Dockerfile instead of three or two?

### PR DESCRIPTION
**Pull request by consideRatio**
By doing this, we reduce the maintenance burden of managing two separate
Dockerfiles. I note that it works to build this Dockerfile using a
RasperryPi 4 having an arm64 architecture.

Closes #57

### CODE REVIEW

**Comment by kmova** [comment]
It will be good to verify this with arm32 as well. 

I see that @dlunch last updated this file. @dlunch do you have an ARM32 setup where this can be verified.

**Comment by dlunch** [comment]
Certainly, I have tested on my arm32 machine, but it fails to build.
```
Step 7/20 : RUN mkdir -p /usr/local     && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_CONFIG=vfs_only -DCMAKE_INSTALL_PREFIX=/usr/local src/     && sed -i 's|@SYSSTATEDIR@/lib/nfs/ganesha|/export|' src/include/config-h.in.cmake         && make         && make install
 ---> Running in f08f0991c861
-- cmake version 3.20
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 11.2.1
-- The CXX compiler identification is GNU 11.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- was set CMAKE_INSTALL_PREFIX = /usr/local
-- Detected a Linux Fedora machine
-- toolchain options processed
-- Found PkgConfig: /usr/bin/pkg-config
-- Compilation from within a git repository. Using git rev-parse HEAD
CMake Warning at CMakeLists.txt:220 (message):
  Unhandled architecture armv7l


-- Building vfs_only configuration
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib/libkrb5.so;/usr/lib/libk5crypto.so;/usr/lib/libcom_err.so;/usr/lib/libgssapi_krb5.so
-- Looking for include file gssapi.h
-- Looking for include file gssapi.h - found
-- Looking for llapi_hsm_state_get_fd in lustreapi
-- Looking for llapi_hsm_state_get_fd in lustreapi - not found
CMake Warning at CMakeLists.txt:598 (message):
  Cannot find lustreapi.  We will only build a dummy lustre fsal.


CMake Warning at CMakeLists.txt:609 (message):
  Cannot find LizardFS client lib.  Disabling lizardfs fsal


-- Looking for open_by_handle in handle
-- Looking for open_by_handle in handle - not found
-- Looking for include file xfs/xfs.h
-- Looking for include file xfs/xfs.h - not found
CMake Warning at CMakeLists.txt:642 (message):
  Cannot find XFS runtime.  Disabling XFS build


-- checking for module 'glusterfs-api>=7.6.6'
/usr/bin/pkg-config: line 8: /usr/bin/armv7hnl-redhat-linux-gnueabi-pkg-config: No such file or directory
--   package 'glusterfs-api>=7.6.6' not found
CMake Warning at CMakeLists.txt:663 (message):
  Cannot find GLUSTER GFAPI runtime.  Disabling GLUSTER fsal build


-- Looking for rgw_mount in rgw
-- Looking for rgw_mount in rgw - not found
-- Found rgw libraries: RGW_LIBRARY-NOTFOUND
-- Could NOT find RGW: Found unsuitable version "0.0.0", but required is at least "1.1.7" (found )
CMake Warning at CMakeLists.txt:743 (message):
  Cannot find supported RGW runtime.  Disabling RGW fsal build


-- Found JeMalloc: /usr/lib/libjemalloc.so
-- checking for module 'dbus-1'
/usr/bin/pkg-config: line 8: /usr/bin/armv7hnl-redhat-linux-gnueabi-pkg-config: No such file or directory
--   package 'dbus-1' not found
CMake Error at cmake/modules/FindPkgConfig.cmake:284 (message):
  A required package was not found
Call Stack (most recent call first):
  cmake/modules/FindPkgConfig.cmake:338 (_pkg_check_modules_internal)
  CMakeLists.txt:805 (pkg_check_modules)


CMake Error at CMakeLists.txt:808 (message):
  Cannot find DBUS libs but requested on command line


-- Configuring incomplete, errors occurred!
See also "/nfs-ganesha/CMakeFiles/CMakeOutput.log".
See also "/nfs-ganesha/CMakeFiles/CMakeError.log".
The command '/bin/sh -c mkdir -p /usr/local     && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_CONFIG=vfs_only -DCMAKE_INSTALL_PREFIX=/usr/local src/     && sed -i 's|@SYSSTATEDIR@/lib/nfs/ganesha|/export|' src/include/config-h.in.cmake        && make          && make install' returned a non-zero code: 1
```

**Comment by kmova** [comment]
Thank you @dlunch. 

@consideRatio - can this PR be closed as it breaks the functionality or covert this PR into building multi-arch builds?

**Comment by consideRatio** [comment]
@kmova sure!

I tried inspecting if the currently published images are arm and/or arm64 compatible with `docker manifest inspect -v <image name>` but failed because k8s.gcr.io required me to have more permissions than I had unlike docker hub would etc.

Do you know if we currently are publishing arm or arm64 compatible images? The Makefile only reference building of arm64 images.

I guess I'm looking for input to conclude if this is a remnant to be removed from the repo or something to actively maintain properly.

**Pull request closed without merging**
