### PR TITLE
Migrate kubernetes-incubator/external-storage/nfs

### PR DESCRIPTION
**Pull request by kmova**
This PR covers the migration of code from https://github.com/kubernetes-incubator/external-storage/tree/master/nfs to this repo. 

The tasks include. 
- [x] import nfs from external-storage repo (git filter-branch --subdirectory-filter nfs -- --all)
- [x] dropped a commit without a CLA that blocked the previous PR to migrate code (#2 ). The changes were not required as the files modified moved to a new location. 
- [x] update README.md (86d889349df72bb4c338190f7bf733881cf0da99)
- [x] update go import path (4347074f0f873f62c1a3cbc9020e13e16208dff9)
- [x] update with image name and registry location (9c3d3dcb18ab33884d3a662e2409e7b269da5f68)
- [x] update vendor (7065b2c8b4ea7b06aca13e385fb856d2cdd7e789)

With the changes made in this PR, the following build commands work. 
- `make container` - generates `quay.io/external_storage/nfs-ganesha-server-and-provisioner:latest`
- `make clean`

Tasks to be done in future PRs: 
- Setup the new quay registry location
- Refactor E2e
- Setup build automation (PROW) to push containers to registry
- Update the docs/deployment.md to reflect new/updated testing scenarios.

### CODE REVIEW

**Comment by nikhita** [comment]
I have manually removed the `do-not-merge/invalid-commit-message` label. 

Lgtm from the cla perspective (from the GitHub management hat on). The `cncf-cla: no` label occurs right now due to missing GitHub users and it's fine to merge manually in such a case.

Please feel free to merge this manually (clicking on the `Merge pull request` button on GitHub) when you are ready. @kubernetes-sigs/nfs-ganesha-server-and-external-provisioner-admins have access to do this.

**Comment by kmova** [comment]
@msau42 @jsafrane @wongma7  - can you help with the manual merge on this one, please.

**Comment by jsafrane** [comment]
okay then, I always wanted to try what the button does...

**Pull request merged**
