### PR TITLE
Attempt to decrease build times

### PR DESCRIPTION
**Pull request by yselkowitz**
* install some missing -devel packages
* drop unused autotools packages
* build with system libntiprc rather than bundled version
* use Ninja instead of Make

### CODE REVIEW

**Comment by yselkowitz** [comment]
Compare github Docker build test jobs:

| Platform | Before | After |
| -------- | ----- | ----- |
| linux/amd64 | 3m10s | 2m9s |
| linux/arm64 | 2h25m10s | 1h12m8s |
| linux/ppc64le | 37m57s | 18m17s |
| linux/s390x | 30m47s | 15m9s |

So the build times are slashed almost in half.  While the prow job works serially (and more slowly), based on the previous run (where amd64 and arm64 completed, and ppc64le got cut off by the timeout), this should succeed this time.

**Review by kvaps — COMMENTED** [review]
Never heard about ninja previously but yeah, why not if it's speed up the build process.
Thank you for your contribution! 
/lgtm

**Review by kvaps — APPROVED** [review]

**Pull request merged**
