### PR TITLE
Rename master to main

### PR DESCRIPTION
**Pull request by ikarldasan**
**What this PR does / why we need it:**
Needed for https://github.com/kubernetes/k8s.io/issues/1597

**Which issue(s) this PR fixes (optional, using fixes #(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged):**
Needed for https://github.com/kubernetes/k8s.io/issues/1597

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by pohly** [comment]
/hold

"release-tools" should not be modified locally. The same change already went into csi-release-tools and will be copied from there.

**Comment by spiffxp** [comment]
@pohly is there anything we can do to help the copy take place? I notice this and a number of other repos are still pending (ref: https://github.com/kubernetes/k8s.io/issues/1597#issuecomment-871796515)

**Comment by pohly** [comment]
> @pohly is there anything we can do to help the copy take place?

The change was merged into csi-release-tools and component owners are welcome to refresh their copy of the repo - anyone can do that. I just tend to do it myself for kubernetes-csi with a script because it is less work overall.

> I notice this and a number of other repos are still pending (ref: [kubernetes/k8s.io#1597 (comment)](https://github.com/kubernetes/k8s.io/issues/1597#issuecomment-871796515))

I already submitted PRs for csi-test and csi-driver-host-path almost a month ago. We just had problems with inactive default reviewers again :cry: I ran my script again now which created new PRs. Perhaps those get more attention.

I didn't update some of the other repos (including this one here) because I didn't know that they were using csi-release-tools and/or whether automatically generated PRs are welcome. I updated my script to also update repos under the kubernetes-sigs org, but ran into issues with "make test" in nfs-subdir-external-provisioner and nfs-ganesha-server-and-external-provisioner. It might just be a Go version mismatch, but I'd prefer if owners of those repos update csi-release-tools themselves because I don't have the bandwidth to deal with repo specific issues.

**Comment by consideRatio** [comment]
> "release-tools" should not be modified locally. The same change already went into csi-release-tools and will be copied from there.

I suggest we close this in favor of https://github.com/kubernetes-csi/csi-release-tools/pull/165 that updates this as part of release-tools directly.

**Comment by pohly** [comment]
> > "release-tools" should not be modified locally. The same change already went into csi-release-tools and will be copied from there.
> 
> I suggest we close this in favor of [kubernetes-csi/csi-release-tools#165](https://github.com/kubernetes-csi/csi-release-tools/pull/165) that updates this as part of release-tools directly.

That nicely avoids the issue of deciding which branch is the latest.

However, someone still needs to take care of updating nfs-ganesha-server-and-external-provisioner.

**Comment by consideRatio** [comment]
> However, someone still needs to take care of updating nfs-ganesha-server-and-external-provisioner.

@pohly yepp! I opened #58 to address what remains here that can be addressed now and not also require an actual rename of branches. I hope that by doing so, #58 can get merged quickly and then the actual migration work related to CI systems etc referencing specific branches can be done with less trouble.

**Comment by consideRatio** [comment]
kubernetes-csi/csi-release-tools#165 has been merged!

**Comment by consideRatio** [comment]
This PR correctly fixes a link, but does it in files that are managed centrally in csi-release-tools, which has got its links fixed at this point via https://github.com/kubernetes-csi/csi-release-tools/pull/165.

Other similar changes for this repo has been made in #58.

Should we close this PR at this point?

**Comment by spiffxp** [comment]
This repo is still showing up in cs.k8s.io as referencing the old links.  What needs to happen to pull in the update of csi-release-tools? Then I think we can close this out

**Comment by kvaps** [comment]
There is another PR which is updating release-tools by the correct way https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/70

However there are some problems with merging it due to broken OWNER dependencies.

We're waiting for @wongma7 to set correct symlink for OWNERS file before we'll be able to merge it.

**Comment by kvaps** [comment]
Closed in favor https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/70#pullrequestreview-757065060
/close

**Pull request closed without merging**
